export enum EEnvKeys {
    // GENERAL
    PORT = 'PORT',
    DEBUG = 'DEBUG',
    NODE_ENV = 'NODE_ENV',
  
    // GSHEET
    GOOGLE_ACCOUNT_EMAIL = 'GOOGLE_ACCOUNT_EMAIL',
    GOOGLE_ACCOUNT_PRIVATE_KEY = 'GOOGLE_ACCOUNT_PRIVATE_KEY',
    GOOGLE_SHEET_ID = 'GOOGLE_SHEET_ID',

    // DATABASE
    DATABASE_URL = 'DATABASE_URL',
    MANGO_LOGIN = 'MANGO_LOGIN',
    MANGO_PASSWORD = 'MANGO_PASSWORD',

    // PROVIDERS
    INFURA_RPC = 'INFURA_RPC',
    PRIVATE_KEY = 'PRIVATE_KEY',

    // AUTH
    SECRETS_JWT = 'SECRETS_JWT',

    // MAGIC LINK
    MAGIC_LINK_API_KEY = 'MAGIC_LINK_API_KEY',
    MAGIC_LINK_SECRET_KEY = 'MAGIC_LINK_SECRET_KEY',

    // FITBIT
    FITBIT_CLIENT_ID = 'FITBIT_CLIENT_ID',
    FITBIT_CLIENT_SECRET = 'FITBIT_CLIENT_SECRET',
    FITBIT_CODE_VERIFIER = 'FITBIT_CODE_VERIFIER',
    FITBIT_CODE_CHALLENGE = 'FITBIT_CODE_CHALLENGE',
  }
  